### ISSUE TITLE
bingo 새로운 고려사항(선택사항)

### ISSUE THREAD

**Issue by csm009177** [KDT-IaaS-Class-One-Group/bingmok#9]
- 쌍삼 룰을 추가
- 여섯개를 놓으면 이기는게 아니다

**Comment by chaeyi0731** [comment]
1. 쌍삼룰 금지는 다시 한 번 확인 해보겠습니다. 지금의 상태로는 4개를 상하로 연결 하여도 ai가 막지 않는 현상이 있습니다.
2. 여섯개 이상 놓았을 시에도 승리 팝업이 나오지 않는 것은 승리 룰을 다시 고쳐 수정 하였습니다. 이제 상하 좌우 대각선 역대각선에서 5개가 이어질 시 승리 팝업이 뜹니다. 

커밋 코드 d1185ec 입니다.

**Comment by chaeyi0731** [comment]
쌍삼룰 추가 완료용 
커밋 2c807e9
